server:
  port: 8081
  servlet:
    context-path: /ecy    #项目访问路径
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml

spring:
  profiles:
    active: dev
  banner:
    location: /banner.txt



